name: plantgl

channels:
  - fredboudon
  - conda-forge

dependencies:
  - openalea.plantgl
  - python=3.8 
  - openalea.pgljupyter 
  - openalea.plantscan3d 
  - alinea.caribu 
  - alinea.astk 
  - matplotlib 
  - pandas 
  - scipy 
  - git